# Generated by Django 2.0.5 on 2019-03-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVxinwenKeyWordsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='关键字')),
                ('weight_count', models.IntegerField(verbose_name='权重')),
            ],
            options={
                'verbose_name': 'CCTV新闻关键字',
                'verbose_name_plural': 'CCTV新闻关键字',
            },
        ),
        migrations.CreateModel(
            name='CCTVxinwenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('link', models.URLField(max_length=255, verbose_name='链接')),
                ('send_count', models.IntegerField(verbose_name='转发数')),
            ],
            options={
                'verbose_name': 'CCTV新闻微博',
                'verbose_name_plural': 'CCTV新闻微博',
            },
        ),
        migrations.CreateModel(
            name='FHWFansModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='昵称')),
                ('location', models.CharField(max_length=255, verbose_name='地区')),
                ('sex', models.CharField(max_length=255, verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='FHWKeyWordsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='关键字')),
                ('weight_count', models.IntegerField(verbose_name='权重')),
            ],
            options={
                'verbose_name': '凤凰网关键字',
                'verbose_name_plural': '凤凰网关键字',
            },
        ),
        migrations.CreateModel(
            name='FHWModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('link', models.URLField(max_length=255, verbose_name='链接')),
                ('send_count', models.IntegerField(verbose_name='转发数')),
            ],
            options={
                'verbose_name': '凤凰网微博',
                'verbose_name_plural': '凤凰网微博',
            },
        ),
        migrations.CreateModel(
            name='SinapapersKeyWordsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='关键字')),
                ('weight_count', models.IntegerField(verbose_name='权重')),
            ],
            options={
                'verbose_name': '新浪微博关键字',
                'verbose_name_plural': '新浪微博关键字',
            },
        ),
        migrations.CreateModel(
            name='SinapapersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('link', models.URLField(max_length=255, verbose_name='链接')),
                ('send_count', models.IntegerField(verbose_name='转发数')),
            ],
            options={
                'verbose_name': '新浪微博微博',
                'verbose_name_plural': '新浪微博微博',
            },
        ),
        migrations.CreateModel(
            name='ZhihuKeyWordsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='关键字')),
                ('weight_count', models.IntegerField(verbose_name='权重')),
            ],
            options={
                'verbose_name': '知乎关键字',
                'verbose_name_plural': '知乎关键字',
            },
        ),
        migrations.CreateModel(
            name='ZhihuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('link', models.URLField(max_length=255, verbose_name='链接')),
                ('send_count', models.IntegerField(verbose_name='转发数')),
            ],
            options={
                'verbose_name': '知乎微博',
                'verbose_name_plural': '知乎微博',
            },
        ),
    ]
